version: "3.2"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: nyu
    container_name: lab-bluemix-cf
    volumes:
      - ..:/app
      - ~/.bluemix/:/home/devops/.bluemix/
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      COUCHDB_HOST: couchdb
      COUCHDB_PORT: 5984
      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-pass}
    networks:
      - dev
    depends_on:
      - couchdb

  # CouchDB Dashboard: http://127.0.0.1:5984/_utils"
  couchdb:
    image: couchdb:latest
    hostname: couchdb
    ports:
      - 5984:5984
    volumes:
      - couchdb:/opt/couchdb/data
    environment:
      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-pass}
    networks:
      - dev

  # Create a few databases needed by CouchDB
  setup:
    image: couchdb:latest
    command: >
      bash -c "echo '*** SETUP: waiting 15 seconds for couchdb to initialize...'; sleep 15
      && curl -X PUT http://admin:pass@couchdb:5984/_users
      && curl -X PUT http://admin:pass@couchdb:5984/_replicator
      && curl -X PUT http://admin:pass@couchdb:5984/_global_changes"
    networks:
      - dev
    depends_on:
      - couchdb   

volumes:
  couchdb:

networks:
  dev:
